Repository milieuinfo/webcomponent-vl-ui-datepicker, pull requests merged in 2019-12, with the labels that each got.

#63 #57 Introduceren value getter en setter
  demo/vl-datepicker.html
  test/vl-datepicker.test.html
  vl-datepicker.src.js
Labels: enhancement

#64 #29 Enter zet niet de waarde in de datepicker bij een manuele ingave
  dist/datepicker.js
Labels: bug

#66 #62 Error en success attributen hebben geen effect
  demo/vl-datepicker.html
  test/vl-datepicker.test.html
  vl-datepicker.src.js
Labels: bug

#67 Update vl-ui-util
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  package.json
  style.css
  style.css.map
  test/docker-compose.yml
  wct.docker.conf.json
  wct.local.conf.json
Labels: maintenance

#68 Revert naar vl-ui-util v2 wegens afwezigheid van refactoring naar nieuwe opzet testen
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: chore
