Repository milieuinfo/webcomponent-vl-ui-datepicker, pull requests merged in 2020-01, with the labels that each got.

#73 Update vl-ui-util
  README.md
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.css.map
  demo/demo.js
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: maintenance

#75 Update naar laatste util
  package-lock.json
  package.json
Labels: bugfix

#78 Verwijder pretest fase (installeren chromedriver). Deze komt via vl-ui-util binnenDepend op core-branch zonder after
  package.json
Labels: chore

#80 Update dependencies
  package-lock.json
  package.json
Labels: bugfix

#81 Update dependencies
  bamboo-specs/bamboo.yml
  demo/demo.css
  demo/demo.css.map
  package-lock.json
  style.css
  style.css.map
  test/docker-compose.yml
Labels: bugfix

#82 Update vl-ui-util
  package-lock.json
Labels: maintenance

#83 Update vl-ui-util
  package-lock.json
Labels: chore
