Repository milieuinfo/webcomponent-vl-ui-datepicker, pull requests merged in 2020-08, with the labels that each got.

#122 Update dependency @govflanders/vl-ui-datepicker to v3.11.5
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#124 Upgrade huisstijl versie 3.11.5
  demo/flatpickr.html
  demo/vl-datepicker.html
  dist/style.css
  dist/style.css.map
  dist/vl-datepicker.js
  dist/vl-datepicker.min.js
  dist/vl-datepicker.src.js
  package-lock.json
  package.json
  src/style.css
  src/style.css.map
  src/vl-datepicker.js
  test/unit/vl-datepicker.test.html
Labels: chore

#125 Introductie value attribuut om de datepicker waarde te kunnen definiëren
  demo/vl-datepicker.html
  dist/vl-datepicker.js
  dist/vl-datepicker.min.js
  dist/vl-datepicker.src.js
  package-lock.json
  package.json
  src/vl-datepicker.js
  test/unit/vl-datepicker.test.html
Labels: enhancement
